const featuredProducts = [
  {
    id: "HANI0001",
    name: "IDHAYA OIL - 500ML BOTTLE",
    price: 130,
    originalPrice: 220,
    image: "/Products/oils/idhayam_oil_500_ml_-removebg-preview.png",
    rating: 4.5,
    reviews: 128,
    discount: 13,
    badge: "sale",
    category: "oil",
    description: "Pure Idhaya Oil with no chemicals, no preservatives. India's finest coconut oil.",
    longDescription: "Experience the pure goodness of Hani's Idhaya Oil - physically refined using traditional methods with zero chemicals or preservatives. Perfect for all your cooking needs, this premium quality oil is sourced from the finest coconuts and processed with utmost care to maintain its nutritional value.",
    images: ["/Products/oils/idhayam_oil_500_ml_-removebg-preview.png", "/Products/oils/idhayam_oil_1000ml_-removebg-preview.png"],
    sizes: ["100ML","200ML","500ML", "1L",],
    sizePrices: {
      "100ML": { price: 30, originalPrice: 50 },
      "200ML": { price: 55, originalPrice: 90 },
      "500ML": { price: 130, originalPrice: 220 },
      "1L": { price: 260, originalPrice: 430 }
    },
    features: [
      "100% Pure and Natural",
      "No Chemicals or Additives",
      "Physically Refined",
      "Rich in Nutrients",
      "Suitable for All Cooking Methods",
      "Long Shelf Life",
    ],
  },
  {
    id: "HANI0002",
    name: "IDHAYA OIL - 1L BOTTLE",
    price: 260,
    originalPrice: 430,
    image: "/Products/oils/idhayam_oil_1000ml_-removebg-preview.png",
    rating: 4.4,
    reviews: 95,
    discount: 12,
    badge: "sale",
    category: "oil",
    description: "Pure Idhayam Oil with no chemicals, no preservatives. India's finest coconut oil.",
    longDescription: "Experience the pure goodness of Hani's Idhayam Oil - physically refined using traditional methods with zero chemicals or preservatives. Perfect for all your cooking needs, this premium quality oil is sourced from the finest coconuts and processed with utmost care to maintain its nutritional value.",
    images: ["/Products/oils/idhayam_oil_1000ml_-removebg-preview.png", "/Products/oils/idhayam_oil_500_ml_-removebg-preview.png"],
    sizes: ["100ML","200ML","500ML", "1L",],
    sizePrices: {
      "100ML": { price: 30, originalPrice: 50 },
      "200ML": { price: 55, originalPrice: 90 },
      "500ML": { price: 130, originalPrice: 220 },
      "1L": { price: 260, originalPrice: 430 }
    },
    features: [
      "100% Pure and Natural",
      "No Chemicals or Additives",
      "Physically Refined",
      "Rich in Nutrients",
      "Suitable for All Cooking Methods",
      "Long Shelf Life",
    ],
  },
  {
    id: "HNAI0003",
    name: "DEVI OIL - 1L BOTTLE",
    price: 150,
    originalPrice: 300,
    image: "/Products/oils/devi_olii-removebg-preview.png",
    rating: 4.6,
    reviews: 156,
    discount: 8,
    badge: "sale",
    category: "oil",
    description: "Pure Devi Oil with no chemicals, no preservatives. Traditional sesame oil.",
    longDescription: "Experience the pure goodness of Hani's Devi Oil - physically refined using traditional methods with zero chemicals or preservatives. Perfect for all your cooking needs, this premium quality oil is sourced from the finest sesame seeds and processed with utmost care to maintain its nutritional value.",
    images: ["/Products/oils/devi_olii-removebg-preview.png"],
    sizes: ["200ML","500ML", "1L",],
    features: [
      "100% Pure and Natural",
      "No Chemicals or Additives",
      "Physically Refined",
      "Rich in Nutrients",
      "Suitable for All Cooking Methods",
      "Long Shelf Life",
    ],
  },
  {
    id: "HANI0004",
    name: "DEVI OIL - 500 ML BOTTLE",
    price: 76,
    originalPrice: 152,
    image: "/Products/oils/devi_olii-removebg-preview.png",
    rating: 4.4,
    reviews: 112,
    discount: 15,
    badge: "sale",
    category: "oil",
    description: "Pure Devi Oil with no chemicals, no preservatives. Traditional sesame oil.",
    longDescription: "Experience the pure goodness of Hani's Devi Oil - physically refined using traditional methods with zero chemicals or preservatives. Perfect for all your cooking needs, this premium quality oil is sourced from the finest sesame seeds and processed with utmost care to maintain its nutritional value.",
    images: ["/Products/oils/devi_olii-removebg-preview.png"],
    sizes: ["200ML","500ML", "1L",],
    sizePrices: {
      "200ML": { price: 40, originalPrice: 80 },
      "500ML": { price: 76, originalPrice: 152 },
      "1L": { price: 150, originalPrice: 300 }
    },
    features: [
      "100% Pure and Natural",
      "No Chemicals or Additives",
      "Physically Refined",
      "Rich in Nutrients",
      "Suitable for All Cooking Methods",
      "Long Shelf Life",
    ],
  },
  {
    id: "HANI0005",
    name: "LUCKY-ALL FLOOR CLEANER - LEMON 500ML",
    price: 120,
    originalPrice: 150,
    image: "/Products/others/Lucky_All-removebg-preview.png",
    rating: 4.4,
    reviews: 89,
    discount: 20,
    badge: "sale",
    category: "cleaners",
    description: "Effective floor cleaner with lemon fragrance.",
    longDescription: "Hani's Lucky-All Floor Cleaner is designed to clean and shine all types of floors. With its powerful formula and refreshing lemon fragrance, it removes dirt, grime, and stains effectively.",
    images: ["/Products/others/Lucky_All-removebg-preview.png"],
    sizes: ["200ML","500ML"],
    features: [
      "Effective Cleaning",
      "Lemon Fragrance",
      "Suitable for All Floor Types",
      "Removes Stains",
      "Long-lasting Shine",
    ],
  },
  {
    id: "HANI0006",
    name: "HAPPY HOME BOTHROOM CLEANER - 500ML",
    price: 140,
    originalPrice: 180,
    image: "/Products/others/happyhome-removebg-preview.png",
    rating: 4.2,
    reviews: 64,
    discount: 22,
    badge: "sale",
    category: "cleaners",
    description: "Powerful bathroom cleaner that removes tough stains.",
    longDescription: "Hani's Bathroom Cleaner is formulated to tackle the toughest bathroom stains and grime. Its powerful ingredients break down soap scum, limescale, and mold for a sparkling clean bathroom.",
    images: ["/Products/others/happyhome-removebg-preview.png"],
    sizes: ["500ML", "1L"],
    sizePrices: {
      "500ML": { price: 140, originalPrice: 180 },
      "1L": { price: 280, originalPrice: 360 }
    },
    features: [
      "Removes Tough Stains",
      "Breaks Down Soap Scum",
      "Eliminates Mold and Mildew",
      "Pleasant Fragrance",
      "Safe for Most Surfaces",
    ],
  },
  {
    id: "HANI0007",
    name: "ALA",
    price: 85,
    originalPrice: 110,
    image: "/Products/others/hero8.jpg",
    rating: 4.3,
    reviews: 47,
    discount: 18,
    badge: "sale",
    category: "cleaners",
    description: "Multi-purpose cleaner for household use.",
    longDescription: "Hani's ALA is a versatile multi-purpose cleaner suitable for various household cleaning tasks. Its effective formula cuts through grease and grime on multiple surfaces.",
    images: ["/Products/others/hero8.jpg"],
    sizes: ["500ML", "1L"],
    sizePrices: {
      "500ML": { price: 85, originalPrice: 110 },
      "1L": { price: 170, originalPrice: 220 }
    },
    features: [
      "Multi-purpose Use",
      "Cuts Through Grease",
      "Safe for Multiple Surfaces",
      "Economical",
      "Pleasant Scent",
    ],
  },
  {
    id: "HANI0008",
    name: "APPALAM 10 PCS",
    price: 25,
    originalPrice: 40,
    image: "/Products/others/hero3.png",
    rating: 4.1,
    reviews: 33,
    discount: 10,
    badge: "sale",
    category: "appalam",
    description: "Crispy and delicious traditional appalam snacks.",
    longDescription: "Hani's Appalam is made from high-quality ingredients using traditional methods. These crispy snacks are perfect for tea time or as a healthy snack option.",
    images: ["/Products/others/hero3.png"],
    sizes: ["10 PCS", "20 PCS", "50 PCS"],
    sizePrices: {
      "10 PCS": { price: 25, originalPrice: 40 },
      "20 PCS": { price: 45, originalPrice: 70 },
      "50 PCS": { price: 100, originalPrice: 150 }
    },
    features: [
      "Traditional Recipe",
      "Crispy Texture",
      "Healthy Snack",
      "Long Shelf Life",
      "No Preservatives",
    ],
  },
  {
    id: "HANI0009",
    name: "HANI'S SCRUB PAD",
    price: 25,
    originalPrice: 40,
    image: "/Products/others/hero7.png",
    rating: 4.1,
    reviews: 33,
    discount: 10,
    badge: "sale",
    category: "other",
    description: "Durable scrub pad for cleaning tough surfaces.",
    longDescription: "Hani's Scrub Pad is designed for heavy-duty cleaning tasks. Its durable construction and abrasive surface make it perfect for removing stubborn dirt and grime from pots, pans, and other surfaces.",
    images: ["/Products/others/hero7.png"],
    sizes: ["Pack of 2", "Pack of 4"],
    sizePrices: {
      "Pack of 2": { price: 25, originalPrice: 40 },
      "Pack of 4": { price: 45, originalPrice: 70 }
    },
    features: [
      "Durable Construction",
      "Abrasive Surface",
      "Heavy-duty Cleaning",
      "Reusable",
      "Effective on Tough Stains",
    ],
  },
]

export default featuredProducts
